### PR TITLE
Add theme selector mockups

### PR DESCRIPTION
**Pull request by mathjazz**
Add mockups for the theme selector to the light theme spec.

### CODE REVIEW

**Review by flodolo — COMMENTED** [review]
One major concern: do we still have plans to localize Pontoon in other languages? If so, the current design for the menu selector is not going to work.

The buttons should also have a tooltip to provide more information, e.g. `Use a dark/light theme in Pontoon`, or `Use a them that matches your system settings`.

For the settings, I feel like the order of selection and explanation should be flipped (you read, then you select).

**Comment by mathjazz** [comment]
> One major concern: do we still have plans to localize Pontoon in other languages? If so, the current design for the menu selector is not going to work.

Added more whitespace. If needed, we can also increase the menu width before we start using localization.

> The buttons should also have a tooltip to provide more information, e.g. `Use a dark/light theme in Pontoon`, or `Use a them that matches your system settings`.

That will not be visible on the mobile UI, so I've also added text above the buttons. I'm not sure it necessary though, especially because the price you pay to click on the wrong button is very low.

> For the settings, I feel like the order of selection and explanation should be flipped (you read, then you select).

Help text position is consistent with other fields and buttons.

**Comment by flodolo** [comment]
> Help text position is consistent with other fields and buttons.

Usually there is a label before a field (left ⇾ right equals top ⇾ bottom). What's below some of them is an additional explanation, but there's already sufficient information in the label itself.

To me, this text feels like the equivalent of the label, not an additional description.

**Comment by mathjazz** [comment]
> but there's already sufficient information in the label itself.

In this case it's best if we just remove it.

**Comment by flodolo** [comment]
> In this case it's best if we just remove it.

I don't understand: are you suggesting removing the description displayed in the current image or something else?

**Comment by mathjazz** [comment]
Yeah.

**Comment by flodolo** [comment]
Personally, I think the description is important (I also never realized how visually confusing I find the selectors for radio buttons).

Let's see if someone else can break the stall.

**Comment by mathjazz** [comment]
I thought by saying "there's already sufficient information in the label itself" you meant that it's not really relevant?

**Comment by flodolo** [comment]
> I thought by saying "there's already sufficient information in the label itself" you meant that it's not really important?

I wonder if the confusion might be due to the fact that I don't consider the current section title (`Appearance`) as a label, because that's not the role section titles have in the rest of the Settings page (they group settings, and each setting has label + optional description).

You wrote:

> Help text position is consistent with other fields and buttons.

My counterargument is that, while such "help text" is placed under a field, the field also has a label that already explains what the field is about. And the label comes before the field. Example:

Screenshot 2023-10-03 alle 11 56 37

In your proposal for settings there is no label, there is only a help description displayed under the selector. I think that description should be above the selector, and basically act as a label. As additional food for thoughts, imagine adding a second setting in this section for "Editor's appearance" (e.g. I want Pontoon Dark but not the editor). How would that work?

BTW, the current menu mock-up uses the same order (description followed by selector).

**Comment by mathjazz** [comment]
OK, so now I think by saying "there's already sufficient information in the label itself" you were talking about the general tune of the Settings page. And not the theme selector specifically, which I thought you were talking about (by "label" I understood the label in the theme buttons). 😄 

Sadly there is no space for the label consistent with the rest of the fields and I honestly don't want to refactor the whole settings UI just for the sake of the theme selector and before taking #2021. And, we actually do have another widget at the bottom of the settings page with only section title serving as the label. I changed its styling in my latest update.

I'd think about placing the "Editor's appearance" if this actually becomes a feature. As for the Profile menu, it's a different story, because we don't have a section title there and there's no other existing UI piece we could reuse there.

All that being said, knowing we'll be refactoring this page sooner or later, I don't have strong opinions about the position of the help text for the theme selector. It's just a theme selector, it's pretty straightforward and if the user for some reason still clicks the wrong button, they will quickly find a way out trouble.

**Review by flodolo — APPROVED** [review]

**Pull request merged**
