### PR TITLE
Fix bug 1614593: Do not error if project created with empty Download prefix field

### PR DESCRIPTION
**Pull request by mathjazz**
The patch is deployed to stage and ready for testing.

### CODE REVIEW

**Comment by mathjazz** [comment]
Hey @flodolo, could you please test this on stage?

**Comment by flodolo** [comment]
It doesn't save, I get the error that the field is required. Is that the expected behavior?

**Comment by mathjazz** [comment]
Yes. I suspect making the filed optional will simplify things you, so I should do it?

**Comment by flodolo** [comment]
> Yes. I suspect making the filed optional will simplify things you, so I should do it?

I see two options:
1) It should be populated automatically, because right now it's a mess to find out.
2) It should be optional.

I'd prefer 2 at this point, with 1 as a long term fix.

**Comment by mathjazz** [comment]
Updated with option #2 and deployed to stage for another round of testing.

**Comment by mathjazz** [comment]
Thanks!

**Comment by mathjazz** [comment]
Pinging @adngdb for a **code** review. :-)

**Pull request merged**
