### PR TITLE
Fix bug 1398852: Add all strings column in the project request view

### PR DESCRIPTION
**Pull request by VishalCR7**
Show total number of strings in the project request view of the team page,
so one can see how big the project is.

Here is the screenshot:
image

### CODE REVIEW

**Comment by VishalCR7** [comment]
@mathjazz can you please review the PR regarding issue [#1398852](https://bugzilla.mozilla.org/show_bug.cgi?id=1398852)

**Comment by VishalCR7** [comment]
@mathjazz please review

**Comment by VishalCR7** [comment]
@mathjazz  done! :grin:

**Comment by VishalCR7** [comment]
My Pleasure Thanks! :sweat_smile:

**Comment by BychekRU** [comment]
Hi @VishalCR7 @mathjazz,
It doesn't work as expected. It shows the project has 3003 strings:

but the project has 143 strings only:

We see the number of strings multiplied by the amount of locales:

**Comment by mathjazz** [comment]
Thanks Victor! We're aware of the issue and are already working on the fix:
https://bugzilla.mozilla.org/show_bug.cgi?id=1442209
https://github.com/mozilla/pontoon/pull/897

**Pull request merged**
