### PR TITLE
Bug 1685565: Switch from Flow to TypeScript

### PR DESCRIPTION
**Pull request by julen**
* Converts all frontend files from Flow to TypeScript (syntax conversion)
* Replaces Flow packages with TypeScript counterparts
* Sets up frontend ESLint w/TypeScript and fixes reported issues (keeps _@typescript-eslint/recommended_ rules disabled for the time being)
* Installs TS type declaration packages for current dependencies (type declarations for 3 packages are not available)
* Adjusts frontend prettier config

Please note this is a pure syntax switch, type declarations need to be adjusted and a bunch of issues need to be fixed (1332 errors as of now).

### CODE REVIEW

**Comment by abowler2** [comment]
> 1332 errors as of now

**Comment by mathjazz** [comment]
Thanks for pulling this effort, @julen! Let us know what help do you need at this stage.

Please also update the `flow` references in the `README` file in the `frontend` folder.

---

Screenshot 2021-02-15 at 13 05 32

**Comment by julen** [comment]
Thanks for the note about the `README`; that's now updated.

I'd like to propose what I already suggested in the bug: let's merge this PR as-is to a separate `typescript` feature branch (the frontend build will inevitably be red until all errors are resolved), and then we can convert individual components (37 in total) in individual PRs, until all are done. At that point we can rebase the branch with the latest commits in `master`, verify all is good, and then merge the entire effort to the mainline branch. We can keep a list of modules in the bug and assign them in an ad-hoc basis (filing 37 individual bugs might be a bit overkill?).

I'm mostly comfortable with going one module at a time because it allows easier change tracking and also because it allows for spontaneous contributions, e.g. I won't have much consecutive time to spare myself this week, I can maybe port 2 modules, or maybe 20 😬.

Happy to hear any other specific suggestions on the way forward, though, @mathjazz, @Pike, @adngdb, @jotes, @abowler2.

**Comment by adngdb** [comment]
That process sounds sane to me! Maybe we could have a document listing all modules, where folks can "assign" themselves to take responsibility for migrating some of them? I'd be happy to squeeze a few in my schedule if I can.

**Comment by Pike** [comment]
Are there good success criteria for a module?

Also, we need answers for react-content-marker (@adngdb ? ), diff-match-patch (exists, but not part of f0c989aaab5f8d6588c36ee763b3e67e6e0e46f3, I wonder why), and react-time-ago (author declined interest before)

**Comment by julen** [comment]
@Pike is no _errors in strict mode_ good enough? or do you have something else in mind?

Re. diff-match-patch, compilation was choking with it so I decided to better handle it when dealing with the affected module (`core/diff` IIRC). If react-time-ago author declined interest in typings, we'll need to write them ourselves.

**Comment by Pike** [comment]
I think the conversation here moved outside of the realm of this PR, let's continue in the bug.

**Comment by mathjazz** [comment]
Closing this one as explained in the bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1685565#c17

Julen, thanks for the great help here - it will help a ton in our transition to TS!

**Pull request closed without merging**
