### PR TITLE
Add tooltip to the TMs' matches count in Machinery tab.

### PR DESCRIPTION
**Pull request by StoyanDimitrov**
Even though my English skills are clearly outstanding I am open to other suggestions.

### CODE REVIEW

**Comment by mathjazz** [comment]
Thanks for the patch!

What if we add titles to all three tabs? Instead of counts, I think we should explain the meaning of the tabs, because they are very cryptic (due to limited space available), so the `title` tag should be added to the `li` element.

Something like this:
* History: Translation history
* Machinery: Translation memory, machine translation & terminology
* Locales: Translations to other languages

Let me know what do you think.

**Comment by StoyanDimitrov** [comment]
The PR's title is misleading, sorry about that. It is adding a title attribute to the count of perfect matches in a single TM provider (i.e. transvision) that is forming a single item in the list of "machinery" suggestions and not the count of all items in this tab.

Even though I've used variety of other similar tools it was not immediately obvious what this number represents and how should I use it. That's the reason behind this PR.

OTOH, what you suggest is even more helpfull and visible to the users and I'll add it with this PR.

**Comment by mathjazz** [comment]
Ouch, sorry. I spoke too fast. You're right, that's not clear at all. I suggest you store the title tag in a variable and then reuse it, so that we keep the text in one place. Maybe the text should be "Number of translation occurrences"?

If you still want to submit a patch I mentioned in my original comment, you can do so in a separate PR.

**Comment by StoyanDimitrov** [comment]
This must be it.

**Comment by mathjazz** [comment]
I suggest we only keep the text in the variable (occurrencesTitle = 'Number of translation occurrences'). Please update that and rebase into a single commit.

Nice work! r+wc

**Comment by mathjazz** [comment]
Thanks!

Could you please [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) the commits?

**Comment by mathjazz** [comment]
Right, I can squash those myself. ;)

Thanks for the patch!

**Pull request merged**
