### PR TITLE
Updated the open sans fonts to version 3.0

### PR DESCRIPTION
**Pull request by DawiAlotaibi**
This was a fix for  #3018

### CODE REVIEW

**Review by eemeli — CHANGES_REQUESTED** [review]
Alas, this does not appear to have fixed the issue. See for example the overlap of the backticks around "See fewer cookie requests" here:

Screenshot 2023-11-23 at 9 59 32

@DawiAlotaibi Did you verify somehow that this appears to work for you locally?

**Comment by eemeli** [comment]
It looks like the problem is visible on fonts.google.com as well:
https://fonts.google.com/specimen/Open+Sans?preview.text=Foo%60bar

**Comment by eemeli** [comment]
It looks like the update on the public site is blocked by this issue: google/fonts#6221

**Comment by DawiAlotaibi** [comment]
I really hopped it would've worked. To bad it is not something I help with

**Comment by mathjazz** [comment]
No worries, @DawiAlotaibi! It's not your fault at all.

Let's proceed once the font gets released publicly.

Thanks for your contribution!

**Comment by mathjazz** [comment]
> Let's proceed once the font gets released publicly.

Seems like the updated version of the font has been released.

**Comment by mathjazz** [comment]
@DawiAlotaibi Would you like to continue with this PR or is it OK is someone takes over?

**Comment by DawiAlotaibi** [comment]
> @DawiAlotaibi Would you like to continue with this PR or is it OK is someone takes over?

Hi @mathjazz Sorry for not responding earlier. I tried to update it by downloading what I assume is the latest version of the fonts from [here](https://fonts.google.com/specimen/Open+Sans/about) but I was not able to verify/test it. So I would think it will be better If someone who knows how to properly test it takes over.

**Comment by mathjazz** [comment]
Thanks @DawiAlotaibi! We'll continue in #3144.

**Pull request closed without merging**
