### PR TITLE
Show keyboard shortcuts in tooltips

### PR DESCRIPTION
**Pull request by mathjazz**
@jotes @Osmose r?

### CODE REVIEW

**Comment by jotes** [comment]
Code looks good for me, however i don't have an environment to check this visually... Is conditional r+ okay in this situation?

**Comment by mathjazz** [comment]
Thanks @jotes, it certainly helps, but I'll wait for @Osmose - our only native speaker. ;)

**Comment by jotes** [comment]
yup, that's definetely good idea!

**Comment by Osmose** [comment]
r+ :D

**Pull request merged**
