### PR TITLE
[WIP] Update react-scripts

### PR DESCRIPTION
**Pull request by mathjazz**
Debugging Travis failure...

### CODE REVIEW

**Comment by mathjazz** [comment]
Looks like it was a temporary Travis issue.

**Comment by adngdb** [comment]
Is this still not worth doing? I mean, it shouldn't hurt to update dependencies. :-) I suggest we reopen!

**Comment by mathjazz** [comment]
If it works [or doesn't require a security update], don't touch anything" they say. :-)

I'll deploy to stage and see how it behaves there.

**Comment by mathjazz** [comment]
Everything seems to be working fine locally and on stage.

**Pull request merged**
