### PR TITLE
Fix Bug 1607158 Upgrade PostgreSQL database version used in travis

### PR DESCRIPTION
**Pull request by anujpandey785**
Updated PostgreSQL 9.4 to PostgreSQL 11.5 in travis

### CODE REVIEW

**Comment by mathjazz** [comment]
Tests are failing with "could not connect to server: Connection refused".

Seems like 11.5 is not supported and we should use 11 instead:
https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version
https://wiki.postgresql.org/wiki/Apt

**Review by mathjazz — COMMENTED** [review]
Looks like you'll also need to update the dist to `bionic`, which [supports PostgreSQL 11](https://docs.travis-ci.com/user/reference/bionic/#databases-and-services).

I tried it myself and it passed:
https://github.com/mozilla/pontoon/pull/1742/files

I still haven't figured out how to make 11.5 work. Maybe @adngdb has ideas?

**Comment by adngdb** [comment]
I would assume that what they use behind version "11" is the latest dot release for that major version, but I have no proof of that. According to the docs, there's not other version available than "11". If what we use in prod is 11.X, then I think it's fine to use 11 in travis.

**Comment by mathjazz** [comment]
Thanks, that make sense.

**Review by mathjazz — APPROVED** [review]
Good work!

**Pull request merged**
