### PR TITLE
Sync should run locales in order of locale code, not language name

### LINKED ISSUE #2286: Sync should run locales in order of locale code, not language name
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1703773](https://bugzilla.mozilla.org/show_bug.cgi?id=1703773)
Bug Reporter: @flodolo
CC:   @mathjazz

Currently sync runs following the alphabetical order of language names, not locale codes. That's not intuitive, and makes debugging sync issues harder.

### PR DESCRIPTION
**Pull request by willianveiga**
Fixes #2286.

### CODE REVIEW

**Review by mathjazz — COMMENTED** [review]
Nice work!

Could you please also sort the `synced_locales` set in the alphabetic order? It used in the "Synced translations for project {} in locales {}." log message.

**Comment by willianveiga** [comment]
Done, @mathjazz.

Should we sort `failed_locales` as well?

Thanks.

**Comment by mathjazz** [comment]
Thanks!

We don't seem to log `failed_locales`, but if you want to include them in the "Failed to sync translations..." log message, than it makes sense to sort them. I'll leave the decision to you.

**Comment by willianveiga** [comment]
It's true. To be honest, I'm not sure how helpful it would be given the context. Leaving it as it is for now.
Thanks again, @mathjazz.

**Review by mathjazz — APPROVED** [review]
Nice work, thanks!

Welcome to Pontoon! :)

**Pull request merged**
