### PR TITLE
 Move location & plural forms from Redux to React Context

### PR DESCRIPTION
**Pull request by eemeli**
~This builds on top of PRs up to #2443, so marking as draft & rebasing once they're merged.~ Edit: Done.

This first refactors a whole bunch of components to be functional and turns all selectors into hooks, so that they may more easily depend on non-redux state. Most custom HOCs are also gotten rid of, with an exception noted in #2440.

With that done, the location state is moved from Redux to its own React Context, providing a custom `Link` component (currently used only in `ResourceProgress`) and concentrating there most of the URL parsing/writing.

As a related next step, a context is also added for pluralForm data, in order to replace its connected-react-router `LOCATION_CHANGE` reducer with a useEffect hook depending on the Location. This allows for dropping all of `translate`'s react-router dependencies.

A minor fix is included project tags, which were being sorted during render, modifying a prop value.

### CODE REVIEW

**Review by mathjazz — COMMENTED** [review]
I'm still looking at some bits of the changeset. So far and on a general note it looks good!

Since it touches pretty much every bit of the translate view, we should test it extensively before shipping. For that purpose, I've deployed it to stage.

Seems like it's broken for non-authenticated users, e.g.:
https://mozilla-pontoon-staging.herokuapp.com/sl/firefox/browser/branding/official/brand.dtd/

I'm also unable to submit translations using the Enter keyboard shortcut.

**Comment by mathjazz** [comment]
Two more things I noticed:
* Keyboard shortcuts for copying from helpers or source string, as well as clearing the editor also don't work.
* Clicking on the notification icon (the bell) breaks the app.

**Comment by eemeli** [comment]
Keyboard shortcuts were broken due to relying on `ev.code`, which is only available starting from React v17. I've now downgraded the TS types to match our actual React v16.

Notification menu was broken due to notifications being typed as `Record<string, any>`, which meant that the in-code presumption of `description.content` always being a string wasn't caught; apparently it's `null` for due dates. Added a test suite for the UserNotification component, but it'd be nice if that typing could be made much stricter, esp. as some fields are currently expected by the code to hold specific shapes. That might need some back-end fixes too, though.

**Review by mathjazz — APPROVED** [review]
We haven't discovered new issues on stage so far. I'll approve and merge to unblock other PRs, but hold off pushing to prod until tomorrow (when the community testing time is due).

**Pull request merged**
