### PR TITLE
FIx #2867 switch to h5bp/html5-boilerplate

### LINKED ISSUE #2867: CSS boilerplate is out of date
As identified in #2864, our CSS boilerplate is originally from [h5bp/html5-boilerplate](https://github.com/h5bp/html5-boilerplate), but has not been kept updated with the upstream.

It would be good to review the changes that have been applied in the last decade or so, and apply them here.

### PR DESCRIPTION
**Pull request by haastrupea**
The content of the content of main.css, normalise.css, and reset.css(modified) from the h5bp/html5-boilerplate(v8.0.0) package to replace the content of boilerplate.css.

Outright removal of reset.css content caused visual changes in the app, so I took the following steps to handle the situation

- I carefully observed visual changes within the app as I removed each reset element with no visual implications

- Elements used in fewer places in the app that need resetting, I  carefully moved their reset  to where they only affect where the elements are used

-  For elements used in too many places, I left their reset as the content of the reset.css in the boilerplate.css file

### CODE REVIEW

**Comment by mathjazz** [comment]
Thanks for the patch @haastrupea!

Could you please fix the failing checks?

**Comment by haastrupea** [comment]
I am glad I could contribute. I made a change that should fix the issues. @mathjazz

**Comment by mathjazz** [comment]
@haastrupea Sorry this is taking so long to review!

This PR will likely conflict with #2957, which is one of our top priority tasks ATM. We plan to land it in the coming days and then we can merge this.

Sorry for inconvenience!

**Comment by haastrupea** [comment]
I just wanted to know if it's okay to go ahead and look up another ticket to work on

**Comment by mathjazz** [comment]
> I just wanted to know if it's okay to go ahead and look up another ticket to work on

Sure thing!

**Comment by mathjazz** [comment]
Hey @haastrupea, I finally look into this PR. Thanks for your patch!

I've deployed it to stage and noticed quite a few differences compared to production. See the below two pages for example.

Dashboard:
https://pontoon.mozilla.org/sl/
https://mozilla-pontoon-staging.herokuapp.com/sl/

Translate view:
https://pontoon.mozilla.org/sl/amo/all-resources/?string=66617
https://mozilla-pontoon-staging.herokuapp.com/sl/amo/all-resources/?string=66617


Sadly the

**Comment by haastrupea** [comment]
Thank you so much...I am going to review and make necessary changes. Thank you once again for taking time out to review and give a very detailed review

**Comment by mathjazz** [comment]
Sorry again for the delay!

**Comment by mathjazz** [comment]
Hey @haastrupea, do you still plan to work on this?

**Comment by mathjazz** [comment]
Hey @haastrupea, just a gentle ping. :) Please let me know if you'd prefer for somebody else to take over. Thanks!

**Comment by mathjazz** [comment]
Closing for now. Let's reopen when work continues.

**Pull request closed without merging**
