### PR TITLE
Fix bug 1681688 - Correctly update generic editor content when the editor is reset.

### PR DESCRIPTION
**Pull request by adngdb**
The issue here was that we did not trigger the `useLoadTranslation` effect when the editor was reset. We do need to trigger it when, and only when, the editor is reset, as that covers all the cases when the editor content needs to be set back to its initial value.

I'm using the opportunity to apply my own rules for hooks: the `useLoadTranslation` hook was only used by one component, so it went back into that component's file.

### CODE REVIEW

**Comment by mathjazz** [comment]
> I'm using the opportunity to apply my own rules for hooks: the `useLoadTranslation` hook was only used by one component, so it went back into that component's file.

Yessssssssss!

**Review by mathjazz — COMMENTED** [review]
Nice work! I'm no longer able to reproduce the bug in any scenario.

However, there's a regression. If you have a string with just one translation, which is approved, and you unapprove it and then try to approve it again, you get a failed check (Unchanged) warning.

**Comment by adngdb** [comment]
> However, there's a regression. If you have a string with just one translation, which is approved, and you unapprove it and then try to approve it again, you get a failed check (Unchanged) warning.

I cannot reproduce that locally. Can you give me more context, or a string that triggers this?

**Comment by mathjazz** [comment]
> I cannot reproduce that locally. Can you give me more context, or a string that triggers this?

Do you have Translate Toolkit checks disabled?

**Comment by mathjazz** [comment]
Sorry, that's my bad. I was approving a translation that is identical to the source string, so it makes sense to show that warning. 😬

**Review by mathjazz — APPROVED** [review]

**Comment by mathjazz** [comment]
*It's the least I can do...*

**Pull request merged**
