### PR TITLE
[WIP] Fix bug 1384139. Add pep8 linter.

### PR DESCRIPTION
**Pull request by jotes**
@mathjazz @adngdb could you look if those changes are acceptable? (i ran autopep8 through all python files). I adjusted pylama to enable pep8.
Currently there's around 40 errors left if we'll accept all autopep8 modifications:
```
(pontoon) ଘ( ᐛ )ଓ ♥ code/pontoon git:(bug-1384139-pep8) ▶ pylama                                        
setup.py:13:18: E251 unexpected spaces around keyword / parameter equals [pep8]
pontoon/wsgi.py:17:1: E402 module level import not at top of file [pep8]
pontoon/teams/tests.py:61:121: E501 line too long (124 > 120 characters) [pep8]
pontoon/projects/tests.py:62:121: E501 line too long (125 > 120 characters) [pep8]
pontoon/base/adapter.py:41:12: E713 test for membership should be 'not in' [pep8]
pontoon/base/views.py:375:12: E713 test for membership should be 'not in' [pep8]
pontoon/base/views.py:481:13: W503 line break before binary operator [pep8]
pontoon/base/views.py:482:13: W503 line break before binary operator [pep8]
pontoon/base/views.py:583:9: W503 line break before binary operator [pep8]
pontoon/base/models.py:57:13: W503 line break before binary operator [pep8]
pontoon/base/models.py:58:13: W503 line break before binary operator [pep8]
pontoon/base/models.py:525:121: E501 line too long (145 > 120 characters) [pep8]
pontoon/base/models.py:536:121: E501 line too long (131 > 120 characters) [pep8]
pontoon/base/models.py:552:121: E501 line too long (121 > 120 characters) [pep8]
pontoon/base/models.py:560:121: E501 line too long (131 > 120 characters) [pep8]
pontoon/base/models.py:1589:121: E501 line too long (121 > 120 characters) [pep8]
pontoon/base/models.py:1640:121: E501 line too long (142 > 120 characters) [pep8]
pontoon/base/models.py:1831:121: E501 line too long (137 > 120 characters) [pep8]
pontoon/base/utils.py:570:12: E713 test for membership should be 'not in' [pep8]
pontoon/base/celeryapp.py:26:1: E402 module level import not at top of file [pep8]
pontoon/base/tests/test_models.py:1438:121: E501 line too long (124 > 120 characters) [pep8]
pontoon/base/tests/test_models.py:1583:121: E501 line too long (124 > 120 characters) [pep8]
pontoon/base/tests/test_models.py:1622:121: E501 line too long (124 > 120 characters) [pep8]
pontoon/base/tests/test_views.py:333:121: E501 line too long (152 > 120 characters) [pep8]
pontoon/sync/models.py:66:121: E501 line too long (123 > 120 characters) [pep8]
pontoon/sync/models.py:81:13: E131 continuation line unaligned for hanging indent [pep8]
pontoon/sync/tasks.py:157:121: E501 line too long (129 > 120 characters) [pep8]
pontoon/sync/tasks.py:213:121: E501 line too long (127 > 120 characters) [pep8]
pontoon/sync/tasks.py:251:121: E501 line too long (123 > 120 characters) [pep8]
pontoon/sync/vcs/models.py:62:121: E501 line too long (131 > 120 characters) [pep8]
pontoon/sync/formats/po.py:113:22: W602 deprecated form of raising exception [pep8]
pontoon/sync/tests/test_vcs_models.py:145:121: E501 line too long (121 > 120 characters) [pep8]
pontoon/sync/tests/test_tasks.py:160:121: E501 line too long (123 > 120 characters) [pep8]
pontoon/sync/tests/formats/test_silme.py:265:9: E265 block comment should start with '# ' [pep8]
pontoon/settings/dev.py:22:121: E501 line too long (126 > 120 characters) [pep8]
pontoon/localizations/views.py:66:121: E501 line too long (133 > 120 characters) [pep8]
bin/make-langpacks.py:10:121: E501 line too long (162 > 120 characters) [pep8]
(pontoon)  💢  0? code/pontoon git:(bug-1384139-pep8) ▶ pylama | wc -l 
37
````

### CODE REVIEW

**Comment by adngdb** [comment]
I very much dislike how this handles long lines, by leaving the closing parenthesis at the end of lines. Also, I think this is an example of something that should be split in many commits, to make it easier to review. I'd love to see one commit with the configuration changes, and then one commit with the fixed. 

One other concern we had while talking about this today is that this is going to cause conflicts that will be a pain to handle for other people. I believe we want to break this down into a lot of smaller commits, maybe pull requests.

**Comment by adngdb** [comment]
Also, if you're interested to work on this, please assign the bug to yourself. I was planning on working on this tomorrow, and we should not both be working on the same thing. :)

**Comment by jotes** [comment]
@adngdb configuration is visible here: https://github.com/jotes/pontoon/blob/810f2e6c43bc379fbb97ae02d1633c2ee85212c0/pylama.ini
I won't mind if you'll take this over -> I'm not sure what's the priority of this task.

**Comment by adngdb** [comment]
Closing this in favor of #653, which is smaller in scope and easier to review. Let's take small steps! :)

**Pull request closed without merging**
