### PR TITLE
Fix bug 1426676: Fix JSON file format bugs

### PR DESCRIPTION
**Pull request by mathjazz**
Deployed to stage:
https://mozilla-pontoon-staging.herokuapp.com/projects/http-dns-mozilla-l10n/

### CODE REVIEW

**Comment by mathjazz** [comment]
@flodolo Could you test it on stage?
https://mozilla-pontoon-staging.herokuapp.com/projects/http-dns/

@jotes Could you review the patch?

**Comment by flodolo** [comment]
I added Italian and made some changes, but it doesn't seem to sync back from stage?

I tried looking at PaperTrail, but got a "Your account has reached 100% log data transfer for this period. Log processing has been paused. See status, change plans via Heroku, or contact support."

**Comment by mathjazz** [comment]
Oh yeah, because it cannot access my personal repo... Let me try to clone it to mozilla-l10n.

**Comment by flodolo** [comment]
To answer your question about indenting: it looks like 2 tabs is more frequent? At least from a few repos I've looked at, and MDN.

**Comment by mathjazz** [comment]
Fixed. Added a new project:
https://mozilla-pontoon-staging.herokuapp.com/projects/http-dns-mozilla-l10n/

Note, you can also see Heroku logs at:
https://dashboard.heroku.com/apps/mozilla-pontoon-staging/logs

**Comment by flodolo** [comment]
Where is this extensionName coming from from exactly?
https://github.com/mozilla-l10n/http-dns/commit/e50d1809a6a871921b8ce545f4709c3228e14776#diff-2993bc276ac7fb919af6768818792868R3

**Comment by mathjazz** [comment]
Here:
https://github.com/mozilla-l10n/http-dns/blob/master/src/_locales/en_US/messages.json#L3

I translated it in Pontoon to trigger sync:
https://mozilla-pontoon-staging.herokuapp.com/it/http-dns-mozilla-l10n/messages.json/?string=179621

**Comment by flodolo** [comment]
I think we overlapped somehow: your changes weren't there when I edited the project, now mine are gone. 

I tried again changing strings, and it worked in both directions. I just hope that wasn't an issue in the PR :)

So far I haven't been able to spot issues.

**Pull request merged**
