### PR TITLE
SYNC button should be disabled when a project is disabled

### LINKED ISSUE #2724: SYNC button should be disabled when a project is disabled
I didn't realize I was on a disabled project this morning, and clicked the SYNC button. I think it would make sense to disable the button if the project is disabled.

### PR DESCRIPTION
**Pull request by willianveiga**
Fixes #2724.

### CODE REVIEW

**Review by mathjazz — COMMENTED** [review]
Nice work!

We should have some visual feedback that the button is hidden. Maybe we should simply hide it?

Also, we should disabled sync also in case Sync Disabled is True.

**Review by mathjazz — COMMENTED** [review]
Thanks, works great!

Nit: perhaps we should remove the brackets, since they aren't really needed?

**Review by mathjazz — APPROVED** [review]

**Comment by flodolo** [comment]
> Also, we should disabled sync also in case Sync Disabled is True.

I'm not sure about this. 

Not sure how other PMs work, but I typically disable SYNC temporarily (e.g. for migrations), but then I want to sync manually once before re-enabling sync.

**Comment by mathjazz** [comment]
Oh, right. You can still sync manually, even if sync is disabled. Let's restore that.

**Pull request merged**
