### PR TITLE
Okpo branch

### PR DESCRIPTION
**Pull request by okpoEkpenyong**

### CODE REVIEW

**Comment by mathjazz** [comment]
Please rebase this branch against the current mozilla/pontoon master. Otherwise it contains changes that have already been merged.

**Comment by okpoEkpenyong** [comment]
I have done the rebase, mathjazz.

**Comment by mathjazz** [comment]
Maybe you didn't force-push afterwards? Because the diff is the same as before:
https://github.com/mozilla/pontoon/pull/1455/files

**Comment by okpoEkpenyong** [comment]
Please I need help on the PR. I did force push and still didnt see any
change.
So I had to delete the branch and create a new PR in another branch. Now I
can see a compare and pull PR button, but
the code still has the old commits which had been merged.

Please what I'm I doing wrong?

**Comment by mathjazz** [comment]
Hi Okpo!

Please see these two articles on how to keep your fork up-to-date with the upstream repository:
https://help.github.com/en/github/getting-started-with-github/fork-a-repo
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by okpoEkpenyong** [comment]
Okay thanks, Mattjazz

**Comment by katherine95** [comment]
Hi, @okpoEkpenyong did you manage to rebase successfully? After updating your forked repo to sync with the main repo, you can use an article I wrote on rebasing to resolve conflicts. 
https://medium.com/@katherinekimetto/git-rebase-rebase-then-merge-86c0b1d18973

**Comment by okpoEkpenyong** [comment]
Thanks Katherine, happy to have you here. I was a bit busy yesterday getting my laptop screen fixed. I'm looking at your article now together with what mattjazz sent. Hopefully, we would fix this today.

**Comment by okpoEkpenyong** [comment]
hello Katherine, I followed the procedure listed in your article. This is what I got:
sudo git pull --rebase origin okpoBranch
From https://github.com/okpoEkpenyong/pontoon
 * branch              okpoBranch -> FETCH_HEAD
Current branch oBranch is up to date.
okpo@okpo-HP-ENVY-15-Notebook-PC:~/pontoon$ sudo git rebase --continuefatal: No rebase in progress?
okpo@okpo-HP-ENVY-15-Notebook-PC:~/pontoon$ sudo git push origin okpoBranch -f
Username for 'https://github.com': okpo.ekpenyong@gmail.com
Password for 'https://okpo.ekpenyong@gmail.com@github.com': 
Everything up-to-date

**Comment by katherine95** [comment]
> hello Katherine, I followed the procedure listed in your article. This is what I got:
> sudo git pull --rebase origin okpoBranch
> From https://github.com/okpoEkpenyong/pontoon
> 
> * branch              okpoBranch -> FETCH_HEAD
>   Current branch oBranch is up to date.
>   okpo@okpo-HP-ENVY-15-Notebook-PC:~/pontoon$ sudo git rebase --continuefatal: No rebase in progress?
>   okpo@okpo-HP-ENVY-15-Notebook-PC:~/pontoon$ sudo git push origin okpoBranch -f
>   Username for 'https://github.com': [okpo.ekpenyong@gmail.com](mailto:okpo.ekpenyong@gmail.com)
>   Password for 'https://okpo.ekpenyong@gmail.com@github.com':
>   Everything up-to-date

Is your forked repo synced with the Pontoon repo?

**Comment by okpoEkpenyong** [comment]
hello Katherine, I followed the procedure listed in your article. This is what I got:
sudo git pull --rebase origin okpoBranch
From https://github.com/okpoEkpenyong/pontoon
 * branch              okpoBranch -> FETCH_HEAD
Current branch oBranch is up to date.
okpo@okpo-HP-ENVY-15-Notebook-PC:~/pontoon$ sudo git rebase --continuefatal: No rebase in progress?
okpo@okpo-HP-ENVY-15-Notebook-PC:~/pontoon$ sudo git push origin okpoBranch -f
Username for 'https://github.com': okpo.ekpenyong@gmail.com
Password for 'https://okpo.ekpenyong@gmail.com@github.com': 
Everything up-to-date


> > hello Katherine, I followed the procedure listed in your article. This is what I got:
> > sudo git pull --rebase origin okpoBranch
> > From https://github.com/okpoEkpenyong/pontoon
> > 
> > * branch              okpoBranch -> FETCH_HEAD
> >   Current branch oBranch is up to date.
> >   okpo@okpo-HP-ENVY-15-Notebook-PC:~/pontoon$ sudo git rebase --continuefatal: No rebase in progress?
> >   okpo@okpo-HP-ENVY-15-Notebook-PC:~/pontoon$ sudo git push origin okpoBranch -f
> >   Username for 'https://github.com': [okpo.ekpenyong@gmail.com](mailto:okpo.ekpenyong@gmail.com)
> >   Password for 'https://okpo.ekpenyong@gmail.com@github.com':
> >   Everything up-to-date
> 
> Is your forked repo synced with the Pontoon repo?

yes, I guess so. Are seeing it differently?

**Comment by mathjazz** [comment]
Closing on behalf of #1464, which was merged in https://github.com/mozilla/pontoon/commit/d84e7e580a9b303164c60c9efc9c3cac705a2eab.

**Pull request closed without merging**
