### PR TITLE
Update README.md - bug 1657587 

### PR DESCRIPTION
**Pull request by readingsnail**
working deploy buttons

### CODE REVIEW

**Comment by mathjazz** [comment]
I don't understand the purpose of this change. Deploy button works fine even without this changeset. Also, with the current implementation it will allow for installing different forks easily instead of hardcoding the upstream repo.

Could you please elaborate why this change is needed?

**Comment by readingsnail** [comment]
so for now, it's send to [this link](https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fwww.heroku.com%2F&template=https%3A%2F%2Fwww.heroku.com%2F) idk, why heroku send to this link. so change a arrived templete

**Comment by mathjazz** [comment]
If you go to https://github.com/mozilla/pontoon and click on the "Deploy to Heroku" button, it takes you to https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fwww.heroku.com%2F&template=https%3A%2F%2Fwww.heroku.com%2F?

**Comment by readingsnail** [comment]
yeah, that's weird thing.

**Comment by mathjazz** [comment]
I can't reproduce it on the latest Nightly.

**Comment by readingsnail** [comment]
that's weird, i using 79 for mac. it's maybe heroku's error, i guess. but very unconvient for first users.

**Comment by jotes** [comment]
I think the issue may be caused by Safari's privacy settings, because the browser doesn't send the HTTP referer header to Heroku (?)
That's my guess, unfortunately I don't have a Mac to check this.

**Comment by mathjazz** [comment]
To avoid breaking deployments from work, let's keep the current behavior:
https://devcenter.heroku.com/articles/heroku-button#adding-the-heroku-button

**Pull request closed without merging**
