### PR TITLE
Fix graphql on DEV server, update django-graphene to 3.2.2

### LINKED ISSUE #3292: GraphQL does not load
http://localhost:8000/graphql fails with a JS error.

### PR DESCRIPTION
**Pull request by flodolo**
Fixes #3292

### CODE REVIEW

**Review by mathjazz — COMMENTED** [review]
The UI now loads, but there's still CSP errors in the Console (related to fonts). It would be nice to clear them while we're here.

Also, I realized http://localhost:8000/graphql/ doesn't load and http://localhost:8000/graphql does. Should we change that, given all other URLs are defined with a trailing `/`?

**Comment by flodolo** [comment]
> Also, I realized [http://localhost:8000/graphql](http://localhost:8000/graphql/) doesn't load and http://localhost:8000/graphql does. Should we change that, given all other URLs are defined with a trailing `/`?

How can you avoid breaking existing scripts using Pontoon API ([example](https://github.com/mozilla-l10n/pontoon-scripts/blob/main/stats/health_report/extract_completion_data.py#L43))?

Is this code enough?

```python
urlpatterns = [
    # Redirect from /graphql to /graphql/
    path("graphql", RedirectView.as_view(url="/graphql/", permanent=True)),

    # GraphQL endpoint. In DEV mode it serves the GraphiQL IDE if accessed with
    # Accept: text/html
    path(
        "graphql/",
        GraphQLView.as_view(schema=schema, graphiql=DEV),
    ),
]
```

**Comment by mathjazz** [comment]
> How can you avoid breaking existing scripts using Pontoon API ([example](https://github.com/mozilla-l10n/pontoon-scripts/blob/main/stats/health_report/extract_completion_data.py#L43))?

I would expect that to "just work": https://docs.djangoproject.com/en/5.1/ref/settings/#append-slash

**Comment by flodolo** [comment]
Should the documentation be updated? 

> I would expect that to "just work": [docs.djangoproject.com/en/5.1/ref/settings#append-slash](https://docs.djangoproject.com/en/5.1/ref/settings/#append-slash)

I don't think it does?

As DEV, `http://localhost:8000/graphql?query={projects{name}}` works and get changed to `http://localhost:8000/graphql/#query=%7B%0A%20%20projects%20%7B%0A%20%20%20%20name%0A%20%20%7D%0A%7D`. 

But If I set it as `DEV=False`, that first URL gets an error (`"Must provide query string."`).

Can we move this part to a separate issue? I'd be happy to have someone more familiar with Django to look into that ;-)

**Comment by mathjazz** [comment]
> Can we move this part to a separate issue? I'd be happy to have someone more familiar with Django to look into that ;-)

Sure, let's leave this out of this PR.

**Review by mathjazz — APPROVED** [review]

**Pull request merged**
