### PR TITLE
Fixes bug 1384139 - Fix all remaining PEP8 violations in Pontoon.

### PR DESCRIPTION
**Pull request by adngdb**
It's a brave new world! 

Note: I need to verify if we run pylama on builds in travis. @jotes @mathjazz do you know if we do?

### CODE REVIEW

**Comment by jotes** [comment]
@adngdb We do from what I recall.

**Comment by adngdb** [comment]
@jotes I added it a while ago, when I started working on [bug 1384139](). This PR removes the two exceptions that we had (and adds a new one that bothered me). 

Btw, I can't add you to reviewers, but feel free to do it if you like!

**Comment by jotes** [comment]
@adngdb Sorry, I forgot :(

**Pull request merged**
