### PR TITLE
Bug 1555259: Copying from Machinery to Source editor results in a broken string

### PR DESCRIPTION
**Pull request by Karskaya**
In editor.js->componentDidUpdate add else if to check the content copied from machinery tab.
In case parsed to fluent message content is Junk, convert it to complex

[Bug 1555259](https://bugzilla.mozilla.org/show_bug.cgi?id=1555259)

### CODE REVIEW

**Comment by Karskaya** [comment]
from this [PR](https://github.com/mozilla/pontoon/pull/1454)
> The value of a Fluent message can be empty if the message has attributes. However, an attribute cannot be empty. It is expected that Fluent complains about that (and we've had to cheat a bit around that in some places).

@adngdb This made me confusing and I did a wrong conclusion about correct system behaviour.

What about rich editor? Machinery value will be inserted into Fluent message, not into an attribute. Should that stay as it is? Would it be rewritten with this issue - [[FTL] Make machinery usable for complex strings](https://bugzilla.mozilla.org/show_bug.cgi?id=1453341 )?

rich

**Comment by Karskaya** [comment]
This fix cause an issue.
If the string in Source editor looks like this:
`serviceworker-worker-debug-forbidden =`
`  .title = Iskanje napak`
After user toggle from advanced to simple FTL mode, instead of rich syntax string receives simple.

**Comment by adngdb** [comment]
Hey @Karskaya, this is a good catch, but it's not related to the bug you are working on. It can be reproduced on master. Also, I don't know if that's actually a bug or not. Anyway, I'll file a bug and we'll see. Thanks!

**Comment by Karskaya** [comment]
> Hey @Karskaya, this is a good catch, but it's not related to the bug you are working on. It can be reproduced on master. Also, I don't know if that's actually a bug or not. Anyway, I'll file a bug and we'll see. Thanks!

@adngdb Thank you! I'll be glad to help with that bug, just in case.

**Pull request merged**
