### PR TITLE
Fix bug 1471534: Truncate missing strings with suggestions

### PR DESCRIPTION
**Pull request by mathjazz**
1st commit removes the unused code.

2nd commit fixes the regression.

### CODE REVIEW

**Comment by mathjazz** [comment]
Deployed to stage. Things look particularly bad if strings contain placeables.

Prod:
https://pontoon.mozilla.org/sl/common-voice/all-resources/?status=unreviewed&string=179060

Stage:
https://mozilla-pontoon-staging.herokuapp.com/sl/common-voice/all-resources/?status=unreviewed&string=179048

/cc @upwinxp

**Comment by flodolo** [comment]
Ugh, I even checked those, and didn't realize the long strings had a suggestion :-\

**Comment by mathjazz** [comment]
While waking up I realized we don't change the truncation if you submit a suggestion to a missing string without suggestions. Now confirmed it's indeed happening. Fixing...

**Comment by mathjazz** [comment]
Fix deployed to stage. Sorry for the mess.

**Pull request merged**
