### PR TITLE
Fix bug 1597733 - Upgrade celery to be compatible with Python 2 and 3

### PR DESCRIPTION
**Pull request by adngdb**

### CODE REVIEW

**Comment by mathjazz** [comment]
Since version 4.0, the default serializer in celery is `json`, which causes the `test_serial_task` to fail with:
```
EncodeError:
<function execute_second_inner_task at 0x7fefe3ec1150> is not JSON serializable
```

Changing the [`task_serializer`](http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_serializer) value back to `pickle` is simple, but it produces another error:
```
EncodeError:
Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

I'll try to refactor the test.

**Comment by adngdb** [comment]
That's great, thanks Matjaz! I shall deploy this to stage and test tomorrow.

**Comment by mathjazz** [comment]
I've deployed the patch to stage for a quick test:
```
./manage.py sync_projects --projects=pontoon-test --force
```

It failed with the same error as the test we had to fix:
```
Traceback (most recent call last):
File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
  R = retval = fun(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/newrelic/hooks/application_celery.py", line 84, in wrapper
  return wrapped(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
  return self.run(*args, **kwargs)
File "/app/pontoon/sync/core.py", line 69, in wrapped_func
  return func(self, *args, **kwargs)
File "/app/pontoon/sync/tasks.py", line 134, in sync_project
  full_scan=force,
File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/task.py", line 427, in delay
  return self.apply_async(args, kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/task.py", line 570, in apply_async
  **options
File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/base.py", line 756, in send_task
  amqp.send_task_message(P, name, message, **options)
File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/amqp.py", line 552, in send_task_message
  **properties
File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 169, in publish
  compression, headers)
File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 252, in _prepare
  body) = dumps(body, serializer=serializer)
File "/app/.heroku/python/lib/python2.7/site-packages/kombu/serialization.py", line 221, in dumps
  payload = encoder(data)
File "/app/.heroku/python/lib/python2.7/contextlib.py", line 35, in __exit__
  self.gen.throw(type, value, traceback)
File "/app/.heroku/python/lib/python2.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
  reraise(wrapper, wrapper(exc), sys.exc_info()[2])
File "/app/.heroku/python/lib/python2.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
  yield
File "/app/.heroku/python/lib/python2.7/site-packages/kombu/serialization.py", line 221, in dumps
  payload = encoder(data)
File "/app/.heroku/python/lib/python2.7/site-packages/kombu/utils/json.py", line 70, in dumps
  **dict(default_kwargs, **kwargs))
File "/app/.heroku/python/lib/python2.7/json/__init__.py", line 251, in dumps
  sort_keys=sort_keys, **kw).encode(obj)
File "/app/.heroku/python/lib/python2.7/json/encoder.py", line 207, in encode
  chunks = self.iterencode(o, _one_shot=True)
File "/app/.heroku/python/lib/python2.7/json/encoder.py", line 270, in iterencode
  return _iterencode(o, 0)
File "/app/.heroku/python/lib/python2.7/site-packages/kombu/utils/json.py", line 59, in default
  return super(JSONEncoder, self).default(o)
File "/app/.heroku/python/lib/python2.7/json/encoder.py", line 184, in default
  raise TypeError(repr(o) + " is not JSON serializable")
Jan 08 03:58:57 mozilla-pontoon-staging app/worker.1 EncodeError: <ResourceQuerySet []> is not JSON serializable
```

**Comment by mathjazz** [comment]
I ended up changing the serializer back to `pickle` to avoid refactoring the sync code without a good reason (it doesn't seem like celery recommends `json` over `pickle` or something).

I was able to sync locally and on stage (python2), so I think we should be good to merge this and

**Pull request merged**
