### PR TITLE
Bug 1688571: fix negative performance side-effects of `FiltersPanel`

### PR DESCRIPTION
**Pull request by julen**
This now only listens for `click` events when the menu is visible by the means of leveraging the `useOnDiscard` hook

### CODE REVIEW

**Comment by julen** [comment]
I haven't been able to verify the proper functioning of the time range filter (not enough data available on my side perhaps?), so another pair of eyes checking that would be appreciated.

**Comment by mathjazz** [comment]
Seems like this was the last component to use `react-onclickoutside`, so we can remove the dependency.

**Comment by julen** [comment]
Yes, I have a separate PR for that.

**Review by mathjazz — APPROVED** [review]
Really nice work, julen! Everything works as expected.

Bonus points for the CSS implementation of the sticky toolbar!

**Pull request merged**
