### PR TITLE
On translation delete, remove corresponding TM entry

### PR DESCRIPTION
**Pull request by mathjazz**
@jotes r?

Fixing bug reported by @jordis.

### CODE REVIEW

**Comment by jotes** [comment]
https://github.com/mozilla/pontoon/blob/master/pontoon/base/tests/test_models.py#L1093

I'm not sure if it's a feature or a bug.

**Comment by mathjazz** [comment]
It's a bug. If the translation is deleted by the user, it should be removed from TM. Otherwise you submit a typo, update it, but it will still show in TM results.

The other case is if the resource or entity gets obsolete. In this case we should keep the TM entry. And we do. And we will after this patch.

I'll update the test.

**Comment by jotes** [comment]
Ok, i forgot that delete method has a differrent context.

**Comment by mathjazz** [comment]
Test updated. Also no need to test for deleting entities (because we don't do that).

**Pull request merged**
