### PR TITLE
Add project view permission to translator groups

### PR DESCRIPTION
**Pull request by haodave**
So that private projects can still be accessible by translator groups of the project.

### CODE REVIEW

**Comment by mathjazz** [comment]
Thanks for the patch! Since there's no issue assigned to this PR, could you please elaborate on what's the motivation for this change?

**Comment by haodave** [comment]
> Thanks for the patch! Since there's no issue assigned to this PR, could you please elaborate on what's the motivation for this change?

We want to allow logged-in translators to be able to contribute translations to private projects (set private for confidential reason), and not having to assign them super user permission.

**Comment by mathjazz** [comment]
@haodave Sorry for the delay in reviewing your PR!

Seems like you are essentially trying to fix https://github.com/mozilla/pontoon/issues/2223 here?

Are you still interested in the development of this feature? The first step would be to rebase the patch against the `main` branch and resolve conflicts.

**Comment by mathjazz** [comment]
Let's reopen when work continues.

**Pull request closed without merging**
