### PR TITLE
Update docs with a apt one-liner

### PR DESCRIPTION
**Pull request by stasm**
I'm setting up Pontoon right now and I think it would be helpful to list all dependencies explicitly in a form of a `apt install` one-liner for people using Ubuntu.  Let's keep this PR open in case I find more things that I'd like to add.

### CODE REVIEW

**Comment by jotes** [comment]
Hi @stasm :D :+1:

**Comment by mathjazz** [comment]
@stasm Welcome to Pontoon. r+

**Comment by stasm** [comment]
eujym9e

**Comment by stasm** [comment]
For anyone interested in setting Pontoon up in a Docker container for _development_, I have some notes here: https://gist.github.com/stasm/97a5b56587fcd5850cd14fe6f91fe7c8.

**Pull request merged**
