### PR TITLE
Bug 1244423 django 1.9.2

### PR DESCRIPTION
**Pull request by jotes**
Hi @mathjazz and @Osmose :)
Could you review? There are two separate commits just for better readability.

### CODE REVIEW

**Comment by jotes** [comment]
Update:
I've updated urls and context_processors references in the settings in the order to remove all RemovedInDjango110Warnings from logs.

**Comment by mathjazz** [comment]
Looks good, nice work! Could you please upgrade to Django 1.9.2, it seems to be available now?

**Comment by jotes** [comment]
@mathjazz That was my initial plan, however after some discussion on the irc:
> <Osmose> jotes: Django 1.9.2 has a known issue with migrations that they're working on fixing
> <Osmose> Stay on 1.9.1 for now
Maybe we should wait until 1.9.3 is released?

**Comment by mathjazz** [comment]
Hm, AFAIK 1.9.1 is vulnerable. @Osmose?

**Comment by jotes** [comment]
@mathjazz Tests are passing on the 1.9.2, so I can update this PR by tomorrow morning.

**Comment by Osmose** [comment]
> Hm, AFAIK 1.9.1 is vulnerable.

> Tests are passing on the 1.9.2, so I can update this PR by tomorrow morning.

1.9.2 if your tests are passing!

**Comment by jotes** [comment]
@mathjazz Hi, could you review again?

**Comment by mathjazz** [comment]
Great job! r+

**Pull request merged**
