### PR TITLE
Bug 1205445. Moved sphinx dependencies to separate file to fix builds

### PR DESCRIPTION
**Pull request by jotes**
This should fix docs @ readthedocs.org . You only need to set requirements file to 'requirements_docs.txt' in advanced settings.
Example build is available here: http://jotes-pontoon.readthedocs.org/en/latest/

@mathjazz @Osmose  could you review?

### CODE REVIEW

**Comment by Osmose** [comment]
I don't have time to test right now but can later, but in the meantime, I'd suggest moving the requirements file to `docs/requirements.txt` to avoid cluttering the root of the repo, and also I'd recommend requiring the doc requirements in `requirements.txt` to avoid having to document how to install the separate documentation requirements. See [here](https://github.com/mozilla/funfactory/blob/master/funfactory/requirements/dev.txt#L5) for an example of what the syntax looks like.

**Comment by jotes** [comment]
@Osmose yup, -r was added in requirements.txt . I've rebased PR - should reflect your suggestions. Thanks for your time :bow:

**Comment by mathjazz** [comment]
This is another great fix @jotes, thank you so much!

I'm also giving @Osmose the opportunity for "more proper praise". ;)

**Comment by Osmose** [comment]
r+, lgtm :D

**Pull request merged**
