### PR TITLE
Fix bug 1646010 - Refactor Editor code to use React hooks

### PR DESCRIPTION
**Pull request by adngdb**
Finally! It took months but I got there: this is, as far as I can tell, fully functional and ready to be pulled in. :relaxed: 

I did my best to rework my previous branch and split the work into smaller and more meaningful commits. The exception is the last commit, because that one includes all the components that depend on each other. But most of the preparation work is in previous commits, which should make that last one easier to review.

This is a lot to take in, as hooks really are a different approach to writing React components, but I like it overall. I had to learn a lot, and did not do any work to pass that knowledge on, so please do ask questions during review. That should serve a good basis for updating the documentation and providing resources to learn more. 

A good place to start learning about hooks is [React's documentation about them](https://reactjs.org/docs/hooks-intro.html). I also appreciated reading this [article going deeper on the `useEffect` hook](https://overreacted.io/a-complete-guide-to-useeffect/) (thanks April :wink: ).

Note that we are losing a bunch of unit tests, for those in `connectedEditor.test.js` I haven't ported elsewhere. If anyone is up for adding more test coverage to this part of the code, that'd be great!

### CODE REVIEW

**Comment by adngdb** [comment]
I've addressed the regressions. All that should be left is performance, including delays in typing in Fluent editors and flashes of the wrong editor when switching entities.

**Comment by adngdb** [comment]
This last commit should solve the performance issues that were reported with [bug 1644202](https://bugzilla.mozilla.org/show_bug.cgi?id=1644202).

**Comment by adngdb** [comment]
This is ready for another round of review! As far as I can tell, it performs well, has no bug that I could find, and has the same feature-set as before. :-)

**Comment by mathjazz** [comment]
Thanks for the update! I've found a few issues:

A. Please fix the tests. :-)

B. I'm getting false unsaved changes warnings:
1. Open https://mozilla-pontoon-staging.herokuapp.com/sl/test-fluent/demo.ftl/?string=223423
2. Click on the previous string in the string list - "File" (string=223594)
3. You get the unsaved changes warning.

C. In the following string, the default cursor position is at the end of the first string. It should be at the beginning:
https://mozilla-pontoon-staging.herokuapp.com/sl/test-fluent/demo.ftl/?string=223638

D. This one seems to not be fixed - Failed Check warning should appear, saying "Plural categories missing: few, two":
https://mozilla-pontoon-staging.herokuapp.com/sl/test-fluent/demo.ftl/?string=223364

E. I've deployed the patch to stage. After you load 3 or 4 more pages in the string list, typing in the editor sadly still becomes slow as reported in [bug 1644202](https://bugzilla.mozilla.org/show_bug.cgi?id=1644202#c2):
https://mozilla-pontoon-staging.herokuapp.com/he/firefox/all-resources/?string=74127

**Comment by mathjazz** [comment]
This patch needs to be rebased due to use of prettier: https://github.com/mozilla/pontoon/commit/0f31239f210c3a4b3fb1593deaff219a876dec2d.

@abowler2 Could you please do that? IIRC @adngdb did it for all open PRs with conflicts when introducing black.

**Comment by abowler2** [comment]
Hey @adngdb ~ Sorry for the disruption in your workflow. I'm happy to do the rebase, but think it may be best if you do it in case there are further conflicts that are unrelated to the prettier changes. However, if you would like me to take care of it just let me know.

**Comment by adngdb** [comment]
Hey all, I managed to rebase this, but I did it in a different branch because I had to squash all my commits. I'll open a new PR when it's ready. I started working on fixing the remaining issues, but sadly I lost context, and those links you pointed to @mathjazz are not available anymore. Could you perhaps test again and give me the strings that caused those issues? I found B, and E is easy to reproduce, but I can't find C and D. Thanks!

**Comment by mathjazz** [comment]
Hey @adngdb, I can't push this branch to stage due to conflicts.

As soon as your rebased PR is up, I can push it to stage and update my comment.

**Pull request closed without merging**
