### PR TITLE
Fix bug 1382538 - Bump python-fluent to 0.4.2

### PR DESCRIPTION
**Pull request by jotes**
@mathjazz @stasm 
I tested that upgrade with my version of pontoon-intro. If you remember more suitable projects/edge-cases - feel free to point them out/review.

### CODE REVIEW

**Comment by mathjazz** [comment]
I think the latest version is 0.5.0.

We should also update fluent-syntax.js as documented:
http://mozilla-pontoon.readthedocs.io/en/latest/dev/contributing.html#integration-with-fluent

Then I'll test with projects on prod.

**Comment by stasm** [comment]
> I think the latest version is 0.5.0.

The latest version of `fluent-syntax` (in JS) is 0.5.0. The latest version of `python-fluent` is 0.4.2.  The versions of those two packages are not lined up and they implement the same syntax support. Sorry if this is confusing: we follow semver and sometimes a change in the API that's specific to the language of the implementation requires a bigger version bump.

**Comment by jotes** [comment]
@mathjazz fluent-syntax is in the newest stable version (0.5.0)

**Comment by mathjazz** [comment]
@stasm Thanks for clarifying!

@jotes Sorry for misguiding you!

The code is r+. Before I approve the PR, I'll test on stage using prod data, because we don't have sufficient test coverage.

**Pull request merged**
