### PR TITLE
Fix bug 1418540: Fix overlay image cutoff in all-resources.

### PR DESCRIPTION
**Pull request by VishalCR7**
I couldn't test it locally but this css addition tends to fix it using developer tools
Reference link : https://pontoon.mozilla.org/fr/fundraising/all-resources/?string=174187
Screenshots : 
Before:
image

After
image

### CODE REVIEW

**Comment by VishalCR7** [comment]
@mathjazz @adngdb can you please review this PR

**Comment by VishalCR7** [comment]
@mathjazz  I have set max width in the same way If i can set max height that will prevent overflow and may prevent overshoot as well

**Comment by mathjazz** [comment]
Let's try. :)

**Comment by VishalCR7** [comment]
@mathjazz  i have set the max height and set the img to center of overlay div and also updated the PR description See if it looks good

**Pull request merged**
