### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mathjazz**
1. Update `lxml`.
2. Update indirect dependencies in `/frontend` within constraints of `/frontend/package.json`.
3. Update indirect frontend dependencies in `/` within constraints of `package.json`.

### CODE REVIEW

**Review by Pike — APPROVED** [review]
lgtm

**Review by Pike — CHANGES_REQUESTED** [review]
Actually, I think there's a bustage in the frontend, which also breaks the python tests as it needs to build it for the py tests to run.

**Review by Pike — APPROVED** [review]
lgtm now. There's one new strict error, I think in src/core/api/base.ts, but I have no clue as to why that would be. Also, it's unclear if it's one new, I only saw that the strict count went up by one, and that one is new. There might be more changes.

**Comment by mathjazz** [comment]
Nice catch with that strict error! Yeah, let's address this separately.

**Pull request merged**
