### PR TITLE
Fix bug 1509079: Update fluent libraries to support fluent syntax 0.8

### PR DESCRIPTION
**Pull request by mathjazz**
**Do Not Merge**

### CODE REVIEW

**Comment by flodolo** [comment]
Any update on this one?

**Comment by mathjazz** [comment]
Waiting for a ping from @stasm when this is good to push to prod.

**Comment by stasm** [comment]
Here's the checklist I've been keeping track of:

- [x] Updated Fluent.jsm in mozilla-central and mozilla-beta (bug [1513958](https://bugzilla.mozilla.org/show_bug.cgi?id=1513958)).
- [x] Updated compare-locales (bug [1512610](https://bugzilla.mozilla.org/show_bug.cgi?id=1512610)).
- [x] Updated python-fluent and compare-locales in mozilla-central and mozilla-beta (bug [1514273](https://bugzilla.mozilla.org/show_bug.cgi?id=1514273)).
- [x] Updated Elmo in production (bug [1515732](https://bugzilla.mozilla.org/show_bug.cgi?id=1515732)).
- [x] Updated `fluent` in Firefox Monitor (https://github.com/mozilla/blurts-server/pull/668).

We're good to go. Thanks!

**Comment by mathjazz** [comment]
Thank you!

**Pull request merged**
