### PR TITLE
Fix uploading files, 1c24429 regression

### PR DESCRIPTION
**Pull request by mathjazz**
Thanks @ibrahimasarr for reporting!

### CODE REVIEW

**Comment by ibrahimasarr** [comment]
Thanks for fixing!
Looks like you cannot updload .po files, only .properties??

**Comment by mathjazz** [comment]
Shouldn't be the case. Just tried Firefox Accounts (.po) and it work.

**Comment by ibrahimasarr** [comment]
Works now. But I did get the message .po Files not supported. Use .properties (in red capitals)

**Comment by mathjazz** [comment]
I guess you tried to upload .po file to a project that uses .properties.

**Comment by ibrahimasarr** [comment]
Actually it was the same .po on the same project (Firefox Accounts) file
that worked later: client.po
Thanks

Le 10 janv. 2017 2:14 PM, "Matjaž Horvat" <notifications@github.com> a
écrit :

I guess you tried to upload .po file to a project that uses .properties.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/pontoon/pull/524#issuecomment-271572428>, or mute
the thread

**Pull request merged**
