### PR TITLE
Add jinja env setup

### PR DESCRIPTION
**Pull request by phlax**
Allows you to use the `url` template tag, to get reversed urls (as you would with django templates)

### CODE REVIEW

**Comment by phlax** [comment]
@mathjazz not sure how you feel about this one - its a convenience to be able to reverse urls in templates, but i can defo work around

**Comment by mathjazz** [comment]
What does that bring us in addition to e.g.:
https://github.com/mozilla/pontoon/blob/master/pontoon/teams/templates/teams/teams.html#L15?

**Comment by phlax** [comment]
nothing 8/ - im wondering why it didnt work for me, and where the url function comes from

ill follow up and see if i can do without...

**Comment by adngdb** [comment]
@phlax can we close this PR?

**Comment by phlax** [comment]
yep, sorry for noise...

**Pull request closed without merging**
