### PR TITLE
Fix bug 1591336 Make colums in bug list sortable

### PR DESCRIPTION
**Pull request by sccofield**
**What does this PR do?**
This pull request fixes the issue [1591336](https://bugzilla.mozilla.org/show_bug.cgi?id=1591336). It adds a sort function to the bug table to make it sortable.

**How can this be tested**
- Go to the bug list page.
- Click on any of the headers to sort the table row.

### CODE REVIEW

**Comment by okpoEkpenyong** [comment]
hello @sccofield, have you been assigned this bug now?

**Comment by mathjazz** [comment]
Hey @okpoEkpenyong, as noted in the bug we're running short on the Mentored bugs.

@katherine95 and @sccofield are now both working on this bug, too.

We understand this is not an ideal solution, but we sadly don't have a better alternative at our disposal.

**Comment by mathjazz** [comment]
Nice work @sccofield, sorting works!

I'd like to ask you to make two more changes to unify the UX on the [Bugs](http://localhost:8000/de/bugs/) and the [Projects](http://localhost:8000/de/) tab:
1. Column titles should have mouse cursor set to pointer and the text should highlight on hover.
1. There should be a small arrow next to the column title indicating the sorting direction.

**Comment by sccofield** [comment]
> hello @sccofield, have you been assigned this bug now?

yea @okpoEkpenyong I had to join in contributing to it, because of the shortage of mentored bugs.

**Comment by okpoEkpenyong** [comment]
Okay. Well done. I didn't know. In any case, I was thinking you should have reached out to me to see how I can resolve the rebasing issue with the PR I made. Again since I was originally assigned the bug, sending a PR should have my name attached too, just a thought o?

**Comment by okpoEkpenyong** [comment]
Okay @mathjazz. Thanks for the explanation.

**Comment by sccofield** [comment]
> Nice work @sccofield, sorting works!
> 
> I'd like to ask you to make two more changes to unify the UX on the [Bugs](http://localhost:8000/de/bugs/) and the [Projects](http://localhost:8000/de/) tab:
> 
> 1. Column titles should have mouse cursor set to pointer and the text should highlight on hover.
> 2. There should be a small arrow next to the column title indicating the sorting direction.

Hi, @mathjazz I have worked on the requested changes to unify the UX.

**Comment by mathjazz** [comment]
> Okay. Well done. I didn't know. In any case, I was thinking you should have reached out to me to see how I can resolve the rebasing issue with the PR I made. Again since I was originally assigned the bug, sending a PR should have my name attached too, just a thought o?

@okpoEkpenyong Please don't worry about the "Assigned to" field too much - it can only be set to one person anyways. We'll make sure everybody who's been contributing to the bug will be mentioned in the commit message that will be merged to `master`. Last but not least, we'll be evaluating Outreachy applications much more thoroughly than by counting the number of bugs fixed.

**Comment by mathjazz** [comment]
Nice work @sccofield! When the tab loads for the first time, you need to set the arrow to the column by which we sort by default (Last Changed). It needs to be turned down.

Also, it seems like the icon shows the opposite direction of sorting for the Last Changed column. When it is turned down, the date on top of the list should be newest.

**Comment by sccofield** [comment]
> Nice work @sccofield! When the tab loads for the first time, you need to set the arrow to the column by which we sort by default (Last Changed). It needs to be turned down.
> 
> Also, it seems like the icon shows the opposite direction of sorting for the Last Changed column. When it is turned down, the date on top of the list should be newest.

Hi, @mathjazz I have added the pointer to the default column. Thanks for the correction on the direction of the pointer. I have effected the change too.

**Pull request merged**
