### PR TITLE
Fix #2256: Replace bug references with links to issues

### LINKED ISSUE #2256: Migrating to GitHub issues
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1688846](https://bugzilla.mozilla.org/show_bug.cgi?id=1688846)
Bug Reporter: @mathjazz
CC:   @abowler2, adrian@gaudebert.fr, @Pike, @flodolo, @julen, keunes@mailbox.org, @Mitch4sho, @MikkCZ, @jotes
Depends on:   [Bug 1728575](https://bugzilla.mozilla.org/show_bug.cgi?id=1728575)

This is a conversation starter to evaluate the feasibility of using GitHub Issues instead of Bugzilla to track bugs for the Pontoon project.

Why GitHub?
* Already used as a critical tool, users don't need another account, barrier to entry is lower.
* It's easier to use. Input form, issues list and search have simpler UX.
* GitHub Issues are easier to reference from within GitHub (PRs, comments, commits...).
* We'll be able to close issues on commit automatically again (see 1486391).
* We'll be able to move roadmap from unmaintained Mozilla Wiki to GitHub.

Why Bugzilla?
* We don't need to do anything.
* We own it.
* Easier to make dependencies with other Mozilla projects (but we barely use that).
* Has established support for (private) security bugs.

### PR DESCRIPTION
**Pull request by mathjazz**

### CODE REVIEW

**Review by Pike — COMMENTED** [review]
Do you think there's a way to get the links to be actually linked on github? That'd be nice. That links resolve in vscode is good, though. Not sure if I'd want to prioritize one over the other.

I've checked out the branch locally, and found quite a few remaining references to bugs. Couldn't find a pattern of what's included in the patch and what's not, though.

**Comment by mathjazz** [comment]
Oh, I only changed references for the ones that were moved (i.e. are still open).

**Review by eemeli — APPROVED** [review]

**Comment by mathjazz** [comment]
No idea how to make issue references linked in the GH source editor.

**Review by Pike — APPROVED** [review]
Ah, OK.

Yeah, LGTM

**Pull request merged**
